#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  9 22:04:45 2020

@author: odindoolittle
"""

import numpy as np

mylist = [1,2,3]
arr1 = np.array(mylist)
print(mylist * 4)
mylist.append(8)
print(mylist)
print(arr1 + 4)

print(np.linspace(arr1, 3))